CREATE DATABASE Nhanvien
ON(
	NAME = 'nv_data'
	, FILENAME = 'D:\CNTT\Code\SQL\EmployeeDB\nv_data.mdf'
	, SIZE = 10MB
	, MAXSIZE = 100MB
	, FILEGROWTH = 5MB
)
LOG ON(
	NAME = 'nv_log'
	, FILENAME = 'D:\CNTT\Code\SQL\EmployeeDB\nv_log.ldf'
	, SIZE = 5MB
	, MAXSIZE = 50MB
	, FILEGROWTH = 2MB
);

CREATE TABLE NhanVien(
	MaNV INT NOT NULL PRIMARY KEY
	, HoTen VARCHAR(50) NOT NULL
	, Phai VARCHAR(50)
	, NgaySinh DATE
	, DiaChi VARCHAR(255)
	, SDT VARCHAR(10)
);

CREATE TABLE KhachHang(
	TenKH VARCHAR(50) NOT NULL
	, MaKH INT IDENTITY(100, 5) NOT NULL PRIMARY KEY
	, DiaChi VARCHAR(255)
	, SDT VARCHAR(10) CHECK(
		SDT LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
		-- LEN(SDT) = 10 AND PATINDEX('%[^0-9]%', SDT) = 0
	)
);

ALTER TABLE NhanVien
ADD Email VARCHAR(100);

ALTER TABLE NhanVien
ALTER COLUMN HoTen VARCHAR(100) NOT NULL;

ALTER TABLE NhanVien
ADD CONSTRAINT NgaySinh CHECK(
	NgaySinh <= GETDATE()
);

-- practice
CREATE TABLE SinhVien(
	MaSV INT NOT NULL PRIMARY KEY
	, HoTen VARCHAR(50) NOT NULL
	, Lop VARCHAR(20)
	, Nganh VARCHAR(20)
	, DiemTB FLOAT
);

ALTER TABLE SinhVien
ADD Email VARCHAR(100);

ALTER TABLE SinhVien
ALTER COLUMN DiemTB DECIMAL(2, 1);

ALTER TABLE SinhVien
DROP COLUMN Nganh;

ALTER TABLE SinhVien
ADD CONSTRAINT DiemTB CHECK(
	0 <= DiemTB AND DiemTB <= 10
);

ALTER TABLE SinhVien
ADD UNIQUE(MaSV);